Cherry pick of ad9592812eb21c502810c4c6ea5df89c4c555c29 failed
stdout:
Auto-merging account_payment_pro_receiptbook/models/account_move.py
CONFLICT (content): Merge conflict in account_payment_pro_receiptbook/models/account_move.py

stderr:
18:22:43.619523 git.c:444               trace: built-in: git cherry-pick ad9592812eb21c502810c4c6ea5df89c4c555c29
error: could not apply ad959281... [FIX] account_payment_pro_receiptbook: Fix the setting of l10n_latam_document_type_id when having receitbook.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/account-payment#636

Related: ingadhoc/odoo-argentina-ee#561
Signed-off-by: Juan José Scarafía <jjs@adhoc.com.ar>
Signed-off-by: rov-adhoc <rov@adhoc.com.ar>